### PR TITLE
Feature 1

### PR DESCRIPTION
**Pull request by TaiwoEnoch**
Design a simple Survey Form.

### CODE REVIEW

**Review by AbayomiOlaoye — CHANGES_REQUESTED** [review]
Hi, @TaiwoEnoch :wave: 
You have done an amazing job implementing previous suggestions, and you've a wonderful project there. However, there are just a few things to fix and you will be good to go.

so_close

## Hightlights
- Great PR message :heavy_check_mark: 
- Age validation working fine :heavy_check_mark: 
- Clean code base :heavy_check_mark: 

## Required :recycle:
screenshot-127 0 0 1_5500-2022 11 23-11_08_52

- [ ] From the image above, there's an outline of green around the form itself - check the arrow-pointers; can you please remove this property as it is not part of the requirement?
- [ ] Also, at the moment, when you look at the highlighted portions of the form, user inputs are almost colliding to the extreme edge of the border, and this is not too good for user experience.
Consider adding some padding elements to the inputs and increase the <code>font-size</code> 
You are doing  a great job, happy coding! :+1:

**Comment by TaiwoEnoch** [comment]
Thank you a lot for always being available to assist and be a good man sir.

Here is the new link to review the project, sir.....

https://github.com/TaiwoEnoch/Survey_Form/

**Review by AbayomiOlaoye — APPROVED** [review]
Hi @TaiwoEnoch :wave: ,
Excellent delivery! This is it, you made it. Now it is time to relax, and merge your code.<br>
**Congratulations, Champ!**

congrats

**Comment by TaiwoEnoch** [comment]
Thanks a lot for your always available sir, I am grateful and I will always be grateful sir.

**Pull request merged**
